### ISSUE TITLE
Copy request button

### ISSUE THREAD

**Issue by lucasdonato** [filiphric/cypress-plugin-api#114]
Hi Filip, it would be interesting to add a button to copy the body/response of each request.

**Comment by filiphric** [comment]
Early versions of the plugin had this button. The only problem with that was that you could only have this button for the very last `cy.api()` command and it had to be the the very last command. it wasn’t very optimal since the experience was different when you traveled back in time in your timeline and it confused people. It also had a weir memory leak issue that I wasn’t able to figure out
