### ISSUE TITLE
issue with using cy.api after cy.origin

### ISSUE THREAD

**Issue by martin131** [filiphric/cypress-plugin-api#124]
I have an issue with this code. After replacing cy.request with cy.api, tests are failing.

```
describe('test', () => {
  it('test', () => {
    cy.origin('https://www.novinky.cz', () => {
      cy.visit("https://www.novinky.cz/p/tiraz")
      cy.contains("Tiráž")
    })

    cy.request({
      method: 'GET',
      url: 'http://httpstat.us/200'
    })
  })
})
```

**Comment by filiphric** [comment]
the reason for this particular test failing is that the origin actually points to `https://cmp.seznam.cz` instead of `novinky.cz`. the error that causes this test to fail is from wrong use of `cy.origin` rather than `cy.api`. closing this for now, but if you are experiencing similar issue, feel free to reopen and provide more info
