### ISSUE TITLE
bug v2.5.0 - Timeout find element

### ISSUE THREAD

**Issue by lucasdonato** [filiphric/cypress-plugin-api#72]
Hi Filip!
I'm using cypress-plugin-api in version **2.5.0**, in my e2 tests and when I make a call to the API it's returning the error below

![image](https://user-images.githubusercontent.com/12953400/203301134-7f0febbf-3b81-4994-ab18-b0cba66b3fad.png)

**example code**
![image](https://user-images.githubusercontent.com/12953400/203301820-cecc9f00-4f2d-4c3b-b0e1-b6a6c916f2a2.png)

**Comment by filiphric** [comment]
Hey @lucasdonato I was trying to replicate this with the exact same properties, but was not able to. can you provide me with some more info? is there anything specific in your `cypress.config.json`?  what are the imports in your support file? could there be something that causes a conflict? when you run your test, do you see the UI, or do you still see the google site? THanks in advance!

**Comment by lucasdonato** [comment]
I created a repository for you to simulate the bug! 😃 
Happens when I make any API call in my global beforeEach (e2e.js file)

https://github.com/lucasdonato/test-cypress-plugin-api

**Comment by filiphric** [comment]
thank you for the repro, that helped quite a lot. since you are trying to combine UI and API test, I would recommend enabling [snapshotOnly mode](https://github.com/filiphric/cypress-plugin-api#snapshot-only-mode) which is built exactly for this kind of use case. however, in the case you showed me it might make sense to show UI even without having the snapshotOnly mode 🤔

**Comment by lucasdonato** [comment]
with **snapshotOnly:true** it worked perfectly. Thank you for your support.
